version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: test-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  vuejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: hanu4u89/docker-vuejs
    ports:
      - "8081:8080"